### ISSUE TITLE
java.lang.UnsatisfiedLinkError:  Issues

### ISSUE THREAD

**Issue by manishmas** [ragnraok/android-image-filter#22]
java.lang.UnsatisfiedLinkError: No implementation found for int[] com.example.cn.Ragnarok.NativeFilterFunc.oilFilter(int[], int, int, int) (tried Java_com_example_cn_Ragnarok_NativeFilterFunc_oilFilter and Java_com_example_cn_Ragnarok_NativeFilterFunc_oilFilter___3IIII)
                                                                                 at com.example.cn.Ragnarok.NativeFilterFunc.oilFilter(Native Method)
                                                                                 at com.example.cn.Ragnarok.OilFilter.changeToOil(OilFilter.java:19)
                                                                                 at com.example.cn.Ragnarok.BitmapFilter.changeStyle(BitmapFilter.java:52)
                                                                                 at com.example.ShatteringActivity$ListAdapterEffect$1.onClick(ShatteringActivity.java:837)
                                                                                 at android.view.View.performClick(View.java:5246)
                                                                                 at android.view.View$PerformClick.run(View.java:21256)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:145)

**Comment by pateljc** [comment]
@manishmas  did u solve this.???
