### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found

### ISSUE THREAD

**Issue by pateljc** [ragnraok/android-image-filter#23]
Caused by: java.lang.UnsatisfiedLinkError: No implementation found for int[] com.example.jigneshjc.portraphoto.portra_FILTER.NativeFilterFunc.oilFilter(int[], int, int, int) (tried Java_com_example_jigneshjc_portraphoto_portra_1FILTER_NativeFilterFunc_oilFilter and Java_com_example_jigneshjc_portraphoto_portra_1FILTER_NativeFilterFunc_oilFilter___3IIII)
                                                       at com.example.jigneshjc.portraphoto.portra_FILTER.NativeFilterFunc.oilFilter(Native Method)
                                                       at com.example.jigneshjc.portraphoto.portra_FILTER.OilFilter.changeToOil(OilFilter.java:21)
                                                       at com.example.jigneshjc.portraphoto.portra_FILTER.BitmapFilter.changeStyle(BitmapFilter.java:36)

**Comment by pateljc** [comment]
ahh i just solve it.
i made mistake in my package name
thank u
